"""Run with Blender --background --python scripts/make-noir-assets.py.
Original project meshes and PCM sound effects; no downloaded assets.
Geometry uses unit bounds to fit the shared gameplay body parts.
"""
import bpy, math, json, pathlib, random, wave, struct

root = pathlib.Path(__file__).resolve().parent.parent
out = root / 'client' / 'assets'
out.mkdir(exist_ok=True)
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
meshes = {}

def loft(name, rings, sides=12):
    vertices = []
    for y, rx, rz in rings:
        for i in range(sides):
            a = 2 * math.pi * i / sides
            vertices.append((rx * math.cos(a), y, rz * math.sin(a)))
    faces = [tuple(reversed(range(sides)))]
    for j in range(len(rings)-1):
        for i in range(sides):
            n = (i+1) % sides
            faces.append((j*sides+i, j*sides+n, (j+1)*sides+n, (j+1)*sides+i))
    faces.append(tuple((len(rings)-1)*sides+i for i in range(sides)))
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(vertices, [], [tuple(reversed(face)) for face in faces])
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    mesh.calc_loop_triangles()
    positions, normals = [], []
    for tri in mesh.loop_triangles:
        for v in tri.vertices:
            positions.extend(round(c, 5) for c in mesh.vertices[v].co)
            normals.extend(round(c, 5) for c in tri.normal)
    meshes[name] = {'positions': positions, 'normals': normals}

loft('torso', [(-.5,.33,.38),(-.3,.38,.45),(.28,.5,.5),(.43,.43,.43),(.5,.23,.3)])
loft('head', [(-.5,.12,.18),(-.33,.31,.34),(0,.48,.48),(.28,.5,.48),(.44,.34,.32),(.5,.08,.1)])
loft('hips', [(-.5,.34,.36),(-.22,.48,.48),(.3,.5,.5),(.5,.4,.43)])
loft('arm', [(-.5,.24,.28),(-.37,.36,.36),(-.05,.35,.35),(.27,.5,.5),(.5,.32,.32)])
loft('leg', [(-.5,.3,.33),(-.1,.35,.38),(.28,.5,.5),(.5,.44,.46)])
loft('foot', [(-.5,.39,.42),(-.28,.5,.5),(.2,.43,.47),(.5,.29,.34)])
loft('coat', [(-.5,.5,.5),(-.44,.5,.5),(.23,.34,.36),(.5,.42,.42)])
loft('hat', [(-.5,.43,.43),(-.2,.5,.5),(.2,.5,.5),(.5,.43,.43)], 16)
loft('crown', [(-.5,.5,.5),(.22,.45,.43),(.5,.32,.36)], 12)
loft('gun', [(-.5,.4,.5),(.5,.4,.5)], 8)
(out / 'noir-meshes.js').write_text('// Generated by scripts/make-noir-assets.py; original project art.\nexport const noirMeshes = '+json.dumps(meshes,separators=(',',':'))+';\n')
source = root / 'art'
source.mkdir(exist_ok=True)
bpy.context.preferences.filepaths.save_version = 0
bpy.ops.wm.save_as_mainfile(filepath=str(source / 'noir-parts.blend'))

rate = 22050
rng = random.Random(1930)
def write_sound(name, duration, synth):
    values = [synth(i/rate, rng.uniform(-1,1)) for i in range(int(rate*duration))]
    peak = max(abs(v) for v in values) or 1
    with wave.open(str(out / (name+'.wav')), 'wb') as f:
        f.setparams((1,2,rate,0,'NONE','not compressed'))
        f.writeframes(b''.join(struct.pack('<h',int(v/peak*27000)) for v in values))

write_sound('heel', .24, lambda t,n: n*math.exp(-t*75)*.7 + math.sin(t*2*math.pi*160)*math.exp(-t*30)*.3)
write_sound('revolver', 1.2, lambda t,n: n*(math.exp(-t*65)+.19*math.exp(-t*5)) + math.sin(2*math.pi*(95*t-23*t*t))*math.exp(-t*13)*.5)
write_sound('plaster', .85, lambda t,n: n*math.exp(-t*5)*(.14+.7*max(0,math.cos(t*91))**12))
write_sound('bell', 2.5, lambda t,n: min(1,t*150)*math.exp(-t*2.3)*(math.sin(2*math.pi*370*t)+.36*math.sin(2*math.pi*973*t)+.17*math.sin(2*math.pi*1531*t)))
print('Generated 10 mesh templates and 4 original sound effects.')
