"""Run with Blender --background --python scripts/make-noir-assets.py.
Original project meshes and PCM sound effects; no downloaded assets.
Geometry uses unit bounds to fit the shared gameplay body parts.
"""
import bpy, math, json, pathlib, random, wave, struct

root = pathlib.Path(__file__).resolve().parent.parent
out = root / 'client' / 'assets'
out.mkdir(exist_ok=True)
scene = bpy.data.scenes.new('STILL / Anonymous sculpture templates')
bpy.context.window.scene = scene
meshes = {}
profiles = {}

def loft(name, rings, sides=8):
    profiles[name] = rings
    vertices = []
    for y, rx, rz in rings:
        for i in range(sides):
            a = 2 * math.pi * i / sides
            vertices.append((rx * math.cos(a), y, rz * math.sin(a)))
    faces = [tuple(reversed(range(sides)))]
    for j in range(len(rings)-1):
        for i in range(sides):
            n = (i+1) % sides
            faces.append((j*sides+i, j*sides+n, (j+1)*sides+n, (j+1)*sides+i))
    faces.append(tuple((len(rings)-1)*sides+i for i in range(sides)))
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(vertices, [], [tuple(reversed(face)) for face in faces])
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    mesh.calc_loop_triangles()
    positions, normals = [], []
    for tri in mesh.loop_triangles:
        for v in tri.vertices:
            positions.extend(round(c, 5) for c in mesh.vertices[v].co)
            normals.extend(round(c, 5) for c in tri.normal)
    meshes[name] = {'positions': positions, 'normals': normals}

# Broad continuous profiles; no bead-like pinching at articulation points.
loft('torso', [(-.5,.37,.40),(.18,.49,.47),(.40,.46,.43),(.5,.22,.28)])
loft('head', [(-.5,.20,.23),(-.30,.37,.38),(.25,.45,.44),(.46,.32,.32),(.5,.17,.18)])
loft('hips', [(-.5,.42,.43),(.05,.46,.45),(.5,.44,.42)])
loft('arm', [(-.5,.39,.40),(0,.46,.46),(.5,.44,.44)])
loft('leg', [(-.5,.42,.42),(0,.47,.46),(.5,.46,.46)])
loft('foot', [(-.5,.39,.42),(-.15,.48,.49),(.5,.32,.32)])
loft('coat', [(-.5,.5,.5),(-.44,.5,.5),(.23,.34,.36),(.5,.42,.42)])
loft('hat', [(-.5,.43,.43),(-.2,.5,.5),(.2,.5,.5),(.5,.43,.43)], 16)
loft('crown', [(-.5,.5,.5),(.22,.45,.43),(.5,.32,.36)], 12)
loft('gun', [(-.5,.4,.5),(.5,.4,.5)], 8)
(out / 'noir-meshes.js').write_text('// Generated by scripts/make-noir-assets.py; original project art.\nexport const noirMeshes = '+json.dumps(meshes,separators=(',',':'))+';\n')
(out / 'sculpture-profiles.js').write_text('// Blender-authored surface rings shared by every anonymous figure.\nexport const sculptureProfiles = '+json.dumps(profiles,separators=(',',':'))+';\n')
source = root / 'art'
source.mkdir(exist_ok=True)
bpy.ops.wm.save_as_mainfile(filepath=str(source / 'noir-parts.blend'),copy=True)

if __name__ == '__main__':
    import runpy
    runpy.run_path(str(root / 'scripts' / 'make-noir-audio.py'), run_name='__main__')
result={'scene':scene.name,'templates':len(meshes)}
