"""Run with Blender --background --python scripts/make-noir-assets.py.
Original project meshes and PCM sound effects; no downloaded assets.
Geometry uses unit bounds to fit the shared gameplay body parts.
"""
import bpy, math, json, pathlib, random, wave, struct

root = pathlib.Path(__file__).resolve().parent.parent
out = root / 'client' / 'assets'
out.mkdir(exist_ok=True)
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
meshes = {}

def loft(name, rings, sides=12):
    vertices = []
    for y, rx, rz in rings:
        for i in range(sides):
            a = 2 * math.pi * i / sides
            vertices.append((rx * math.cos(a), y, rz * math.sin(a)))
    faces = [tuple(reversed(range(sides)))]
    for j in range(len(rings)-1):
        for i in range(sides):
            n = (i+1) % sides
            faces.append((j*sides+i, j*sides+n, (j+1)*sides+n, (j+1)*sides+i))
    faces.append(tuple((len(rings)-1)*sides+i for i in range(sides)))
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(vertices, [], [tuple(reversed(face)) for face in faces])
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    mesh.calc_loop_triangles()
    positions, normals = [], []
    for tri in mesh.loop_triangles:
        for v in tri.vertices:
            positions.extend(round(c, 5) for c in mesh.vertices[v].co)
            normals.extend(round(c, 5) for c in tri.normal)
    meshes[name] = {'positions': positions, 'normals': normals}

loft('torso', [(-.5,.33,.38),(-.3,.38,.45),(.28,.5,.5),(.43,.43,.43),(.5,.23,.3)])
loft('head', [(-.5,.12,.18),(-.33,.31,.34),(0,.48,.48),(.28,.5,.48),(.44,.34,.32),(.5,.08,.1)])
loft('hips', [(-.5,.34,.36),(-.22,.48,.48),(.3,.5,.5),(.5,.4,.43)])
loft('arm', [(-.5,.24,.28),(-.37,.36,.36),(-.05,.35,.35),(.27,.5,.5),(.5,.32,.32)])
loft('leg', [(-.5,.3,.33),(-.1,.35,.38),(.28,.5,.5),(.5,.44,.46)])
loft('foot', [(-.5,.39,.42),(-.28,.5,.5),(.2,.43,.47),(.5,.29,.34)])
loft('coat', [(-.5,.5,.5),(-.44,.5,.5),(.23,.34,.36),(.5,.42,.42)])
loft('hat', [(-.5,.43,.43),(-.2,.5,.5),(.2,.5,.5),(.5,.43,.43)], 16)
loft('crown', [(-.5,.5,.5),(.22,.45,.43),(.5,.32,.36)], 12)
loft('gun', [(-.5,.4,.5),(.5,.4,.5)], 8)
(out / 'noir-meshes.js').write_text('// Generated by scripts/make-noir-assets.py; original project art.\nexport const noirMeshes = '+json.dumps(meshes,separators=(',',':'))+';\n')
source = root / 'art'
source.mkdir(exist_ok=True)
bpy.context.preferences.filepaths.save_version = 0
bpy.ops.wm.save_as_mainfile(filepath=str(source / 'noir-parts.blend'))

import runpy
runpy.run_path(str(root / 'scripts' / 'make-noir-audio.py'), run_name='__main__')
